### ISSUE TITLE
Investigate Unity asset store license to make sure we are free and clear to use this asset.

### ISSUE THREAD

**Issue by JacobChrist** [VRCreatorAcademy/vr-creator-academy-collab#29]
https://assetstore.unity.com/packages/templates/packs/revolver-kit-vr-no-code-needed-103118

**Comment by DCerminara** [comment]
Andrew Zimmer's comment on his asset: (found on his Overview page on the Unity Asset store)

"Between a full-time job, side projects, and taking care of my family, I just don't have time to support Revolver Kit as fully as I'd like. With this in mind, I've decided to open source this Asset. Please download and enjoy!"

**Comment by JacobChrist** [comment]
Sounds good.
