### ISSUE TITLE
Build a shooting gallery level

### ISSUE THREAD

**Issue by JacobChrist** [VRCreatorAcademy/vr-creator-academy-collab#30]

**Comment by DCerminara** [comment]
I intend to tackle a very rudimentary shooting gallery setup, using Andrew Zimmer's VR Revolver and basic animations and scripting.  This will provide a basic framework for a shooting mechanic for all that I'm sure the more elegant coders among us can refine and improve if so desired.

**Comment by DCerminara** [comment]
Scene as is works with OpenXR.  No win/loss conditions, randomizing of 'BadGuy' needs work.  Oculus hands imported for placeholder models, no animations applied.  Plenty of function left to discover in Mr. Zimmer's revolver, including physical shells/flick reloads, etc.  Level design could be expanded beyond a simple horizontal plane if so desired.  Lots of fun regardless!

**Comment by JacobChrist** [comment]
This has been added.
