### ISSUE TITLE
cornhole - tree model(s)

### ISSUE THREAD

**Issue by JacobChrist** [VRCreatorAcademy/vr-creator-academy-collab#42]
Here is my current thinking...  Cornhole is a two player game and it needs networking.  So what I think we should do is build out the corn hole scene as best we can.  Put it in a pretty backyard with a picked fence and a house (that you can't enter).  There should be a nice lawn and some yard accouterments such as a lawn, shrubs, trees, furniture and BBQ. Maybe even some critters that run by every once and a while.  I posted a link to corn-hole rules.  There are some interesting challenges here.  Scoring is dependent on where your bags lands and weather they go through the wholes.  Also, scoring is based on not just your bags but your opponents bag locations.  We need a score board (maybe a chalk board or white board).  To connect players we will need a lobby and a relay server.  There is a lot here but its so small once it is working it will be a good jumping off point.
Also, I don't know if you have tried to throw the cube in the scene, but it doesn't go very far.  Some physics or scripting will be needed to make it feel right.  I about an pulling my arm out of the socket to get the cube to go what feels like a couple of feet (2/3 m).  If I was throwing that hard IRL the bag would go over the fence.  Hehe.  What if you had an angry neighbor that throws the bag back if it goes over the fence?

**Comment by Chris-N** [comment]
Hey Jacob, I'll take a swing at making a tree 🌲

**Comment by JacobChrist** [comment]
Done!

**Comment by Chris-N** [comment]
Alright I got us a tree but a little confused as to where it should go.

Am I putting the tree.blend file in `vr-creator-academy-collab/Art/cornhole/`?
I also noticed there's a `vr-creator-academy-collab/vr-creator-academby-collab-unity-project/Assets/Core/Art/cornhole/` which has .fbx files.

So are we suppose to put .blend files in the ...-collab/Art/cornhole and also put .fbx in the ...Core/Art/cornhole?

Here's a preview of the tree as well, any feedback on that is welcomed too.
![tree_scale](https://user-images.githubusercontent.com/3195881/195954469-06dc367a-0208-4e4e-8923-a5c4efa976fd.png)

**Comment by JacobChrist** [comment]
I created the folder outside of the project to hold source files for the art in case it needed to be modified in the future. Then I put the actual asset that's used in the project in the asset folder.

**Comment by JacobChrist** [comment]
I'm not sure that this is the best way to do it I've done it other ways but this is the way I started it but we could always change it.

Good looking tree by the way.

**Comment by Chris-N** [comment]
So the PR is up. I just went along with having the two separate files in the project from source to actual. I don't know the best way to manage those assets but for now this should be fine until we run into any issues or better suggestions later. At least the project keeps moving

**Comment by JacobChrist** [comment]
Right on, I will check it out in a couple of hours.

**Comment by DavidJH2** [comment]
> Alright I got us a tree but a little confused as to where it should go.
> 
> Am I putting the tree.blend file in `vr-creator-academy-collab/Art/cornhole/`? I also noticed there's a `vr-creator-academy-collab/vr-creator-academby-collab-unity-project/Assets/Core/Art/cornhole/` which has .fbx files.
> 
> So are we suppose to put .blend files in the ...-collab/Art/cornhole and also put .fbx in the ...Core/Art/cornhole?
> 
> Here's a preview of the tree as well, any feedback on that is welcomed too. ![tree_scale](https://user-images.githubusercontent.com/3195881/195954469-06dc367a-0208-4e4e-8923-a5c4efa976fd.png)

Can we prefer .blend files over .fbx files since they are quicker and easier to edit in Blender?

**Comment by Chris-N** [comment]
> 
> Can we prefer .blend files over .fbx files since they are quicker and easier to edit in Blender?

I first tried this by applying my .blend file in the Core directory but within Unity I ran into problems. I got an error of "Blender is not found" and when I drag this new prefab onto the scene it would only show an empty GameObject. So I onced the other models were .fbx and when I exported it out as that it could now display properly within Unity.

All that to say, that is why I went with .fbx and later noticed the other directory with original .blend files too.

**Comment by Chris-N** [comment]
Not sure how these issues are setup but the status should be closed due to the merge from https://github.com/VRCreatorAcademy/vr-creator-academy-collab/pull/55

Don't want to keep the issue open to confuse everyone.

**Comment by DavidJH2** [comment]
No worries! 🙂

That was more of a project wide question.

I can show you how to fix that when I have time if you would like.

**Comment by JacobChrist** [comment]
Yeah, closing.

**Comment by DavidJH2** [comment]
Are we supposed to close our own issues or is Jacob supposed to do it?

I closed my own; should I have let Jacob close it?

**Comment by JacobChrist** [comment]
I don't think it matters who closes it if its done, we can always reopen it or open a new issue later.

**Comment by DavidJH2** [comment]
👍

**Comment by JacobChrist** [comment]
@Chris-N I tried to bring the tree prefeb into a scene and I don't see colors / materials.  The material on the prefab are just white..  Did you try to import?  Do you have time to fix this?

![image](https://user-images.githubusercontent.com/198251/202362578-7cf3a209-5e34-401c-ba64-bf93efbf3b38.png)

**Comment by Chris-N** [comment]
> @Chris-N I tried to bring the tree prefeb into a scene and I don't see colors / materials.  The material on the prefab are just white..  Did you try to import?  Do you have time to fix this?
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/198251/202362578-7cf3a209-5e34-401c-ba64-bf93efbf3b38.png)
> 
> 

Yes, I did import it before but I think it just needs a property set for it to apply the texture. I'll look into it again and let you know

**Comment by Chris-N** [comment]
@JacobChrist sorry for the delay been sick this week but getting better.

In any case, here's the [PR](https://github.com/VRCreatorAcademy/vr-creator-academy-collab/pull/58) which addresses my first PR that never added the tree material file. I can't believe I dropped the ball there but this should correct it now.
